dev:
  EnvVariables:
    STAGE: dev
    DB_USER_NAME: Abhilash
    DB_PASSWORD: password123
test:
  EnvVariables:
    STAGE: test
    DB_USER_NAME: Abhilash
    DB_PASSWORD: password123
prod:
  EnvVariables:
    STAGE: prod
    DB_USER_NAME: Abhilash
    DB_PASSWORD: password123
